/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fil.rouge;

import fil.rouge.utils.DBManager;

public class App {
    

    public static void main(String[] args) {
        Ressource ressource = getRessourceById(4);

        System.out.println(ressource.getNom());
    }


    public static Ressource getRessourceById(int id) {
        DBManager.open();
        Ressource ressource = DBManager.session.getReference(Ressource.class, id);
        DBManager.close();
        return ressource;
    }
}
